#!/usr/bin/env bash
set -e
REPO_NAME="$1"
if [ -z "$REPO_NAME" ]; then
  echo "Использование: ./deploy_github.sh <repo-name>"
  exit 1
fi
# Проверка gh
if ! command -v gh >/dev/null 2>&1; then
  echo "Требуется gh (GitHub CLI). Установите: https://cli.github.com/"
  exit 1
fi
git init
git add -A
git commit -m "Initial commit: site generated by assistant"
gh repo create "$REPO_NAME" --public --source=. --remote=origin --push
# Создаём GitHub Pages workflow (если нужно, уже включено через actions)
echo "Репозиторий создан и запушен. Перейдите в настройки GitHub → Pages, если нужно изменить ветку."
